/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/*
 * @brief: Main program where application is run, is constantly processing from the terminal and uses all other
 * files created in the program to interact with the user and the serial terminal
 */
#include <stdio.h>
#include "usart.h"
#include <string.h>
#include "processor.h"
#include "led.h"

int main(void)
{
	/*
	 * Clocks: Processor = 48 Mhz. AHB = 48 MHz. APB = 24 MHz.
	 *
	 */
	// initialize peripherals
	led_init();
	usart_init();
	printf(">> Welcome to SerialIO!\n\r");
	// get rid of empty buffer used in getchar()
	setvbuf(stdin, NULL, _IONBF, 0);
	while (1) {
		// program keeps on processing from the USART terminal
		process_readline();
	}
}
