/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/*
 * @brief: Main program where application is run, is constantly processing from the terminal and uses all other
 * files created in the program to interact with the user and the serial terminal
 */
#include <stdio.h>
#include "usart.h"
#include <string.h>

#include "cash_register.h"
#include "mfrc522.h"
#include "spi.h"
#include "timing.h"



int main(void)
{
	/*
	 * Clocks: Processor = 48 Mhz. AHB = 48 MHz. APB = 24 MHz.
	 *
	 */
	// initialize peripherals
	usart_init();
	// get rid of empty buffer used in getchar()
	setvbuf(stdin, NULL, _IONBF, 0);
	// Initialize SPI communication
	spi_init();

	// Initialize systick for 100ms interrupts
	systick_init();
	// Intialize mfrc522 for SPI communication and detecting card
	mfrc522_init();
	// Print the initial menu
	print_menu();
	// Keep processing what the user inputs in the keyboard
	while(1)
	{
		process_char();
	}
}
